//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICH_HOC
    {
        public int LichID { get; set; }
        public Nullable<int> HocVienID { get; set; }
        public Nullable<int> PTID { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
        public string ThuHoc { get; set; }
        public string BuoiHoc { get; set; }
    
        public virtual HOCVIEN HOCVIEN { get; set; }
        public virtual PT PT { get; set; }
    }
}
