//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class THIETBI
    {
        public int ThietBiID { get; set; }
        public string TenThietBi { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> SoLuongTot { get; set; }
        public Nullable<int> SoLuongHong { get; set; }
    }
}
